name: Package Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Tarball with Submodules
        run: |
          tar --exclude=".git" -czf grpc-extension.tar.gz *

      - name: Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: grpc-extension.tar.gz